Repository Kiro47/MTU-Transfer-Course-Gatherer, pull requests merged in 2020-01, with the labels that each got.

#9 Fix use of old variable name in sync script from commit 371e7a6
  course_gather/management/commands/custom_db_sync.py
Labels: bug

#11 Add htmllib5 depending to requirements.txt
  requirements.txt
Labels: READY, bug

#10 Fix system level python path force
  banwebScrape.py
Labels: bug

#12 Address issue #8, add django filters
  course_gather/filters.py
  course_gather/settings/base.py
  course_gather/viewsets.py
Labels: READY, enhancement

#14 Fix trailing s in requirements.txt
  requirements.txt
Labels: bug

#16 Add migrations dir
  course_gather/migrations/__init__.py
Labels: READY, bug
