Repository Kiro47/MTU-Transfer-Course-Gatherer, pull requests merged in 2020-06, with the labels that each got.

#50 Speed up frontend
  Dockerfile
  course_gather/settings/base.py
  course_gather/settings/prod_settings.py
  scripts/startup
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
Labels: READY, enhancement

#54 Change viewsets to be readonly
  course_gather/viewsets.py
Labels: bug

#53 Address issue #43 add Django logging to base config
  course_gather/settings/base.py
Labels: enhancement

#34 Add base CLI setup
  .gitignore
  banwebScrape.py
  docs/development.md
  scraper/Logger.py
  scraper/args.py
  scraper/transfers/data_types.py
  scraper/transfers/file_utils.py
  scripts/bootstrap
Labels: READY

#55 Update Django and django-filter dependencies
  requirements.txt
Labels: dependencies
