Repository Kiro47/MTU-Transfer-Course-Gatherer, pull requests merged in 2020-05, with the labels that each got.

#26 Refactor/banweb scrape
  .gitignore
  banwebScrape.py
  requirements.txt
  scraper/Logger.py
  scraper/transfers/data_gathering.py
  scraper/transfers/data_scraping.py
  scraper/transfers/data_types.py
  scraper/transfers/file_utils.py
Labels: READY, enhancement

#23 UI Touchup
  .eslintrc
  .github/workflows/reactjs-linting.yml
  .gitignore
  package-lock.json
  package.json
  webapp/.env.example
  webapp/README.md
  webapp/index.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/action-types.js
  webapp/src/actions.js
  webapp/src/actions/courses.js
  webapp/src/config.js
  webapp/src/configure-store.js
  webapp/src/index.js
  webapp/src/reducers.js
  webapp/src/reducers/courses.js
  webapp/src/reducers/index.js
  webapp/src/store/configureStore.js
  webapp/src/ui/.page.js.bak
  webapp/src/ui/components/courses-list.js
  webapp/src/ui/components/coursesList.js
  webapp/src/ui/components/theme-selector.js
  webapp/src/ui/courses.js
  webapp/src/ui/page.js
Labels: enhancement

#33 Improvement/issues-29-31
  .dockerignore
  Dockerfile
  README.md
  course_gather/conf/gunicorn.ini
  course_gather/settings/base.py
  course_gather/settings/dev_settings.py
  course_gather/settings/local_settings.py
  course_gather/settings/prod_settings.py
  course_gather/urls.py
  requirements.txt
  run_tests
Labels: READY, enhancement

#42 Split Dockerfile into prod / dev
  .dockerignore
  .github/workflows/django-testing.yml
  .github/workflows/pep8-linting.yml
  Dockerfile
  Dockerfile.dev
  README.md
  course_gather/conf/supervisord.conf
  course_gather/settings/base.py
  course_gather/settings/dev_settings.py
  course_gather/settings/local_settings.py
  course_gather/settings/prod_settings.py
  course_gather/urls.py
  docs/README.md
  docs/deployment.md
  docs/development.md
  docs/docker-compose.yml
  docs/screenshot.png
  requirements.txt
  scripts/bootstrap
  scripts/run_tests
  scripts/startup
Labels: READY

#46 Misc improvements
  course_gather/settings/base.py
  course_gather/settings/dev_settings.py
  course_gather/settings/local_settings.py
  course_gather/urls.py
  requirements.txt
  webapp/public/favicon.ico
  webapp/public/index.html
  webapp/public/logo192.png
  webapp/public/logo512.png
  webapp/public/manifest.json
  webapp/src/actions.js
Labels: READY
